// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class RegistraceTest {
  private WebDriver driver;
  private final String BASE_URL = "http://localhost:81/registracia.php";
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
//    driver.quit();
  }
  @Test
  public void registrace() {
    driver.get(BASE_URL);
    driver.findElement(By.name("email")).sendKeys("zdenek@seznam.cz");
    driver.findElement(By.name("name")).sendKeys("Zdenek");
    driver.findElement(By.name("surname")).sendKeys("Ptak");
    driver.findElement(By.name("password")).sendKeys("xxx1234");
    driver.findElement(By.name("password-repeat")).sendKeys("xxx1234");
    driver.findElement(By.id("checkbox")).click();
  }
}
